import dbmodels.adminDBModel
import dbmodels.notebookDBModel
import dbmodels.problemDBModel
import dbmodels.problemsetDBModel
import dbmodels.scoreDBModel
import dbmodels.userDBModel
import dbmodels.settingsDBModel
